# Generated by Django 4.0.6 on 2022-09-23 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0002_alter_categories_user_alter_spentmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spentmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainpages.categories'),
        ),
        migrations.AlterField(
            model_name='spentmodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
