# Generated by Django 4.0.6 on 2022-09-24 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0003_spentmodel_category_alter_spentmodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='spentmodel',
            name='day_buyed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
